working

diff --git a/git-fancy-push b/git-fancy-push
--- a/git-fancy-push
+++ b/git-fancy-push
@@ -3,22 +3,128 @@
 set -euo pipefail
 
 VERBOSE=
-if [ "$#" -gt 0 ] && [ "$1" = "--execute" ]; then
-    commit_to_json() {
-        git cat-file commit "$SHA1" | awk '
-        ' | jq "$(git cat-file commit "$SHA1" | awk '')"
-    }
-
+if [ "$#" -gt 0 ] && [ "$1" = "--update-ref" ]; then
     shift
     [ "$1" = "--verbose" ] && VERBOSE=YES && shift
-    [ -n "$VERBOSE" ] && printf 'args: %q\n' "$@" >&2
+    [ -n "$VERBOSE" ] && printf '%q' "$0" >&2
+    [ -n "$VERBOSE" ] && printf ' %q' "$@" >&2
+    [ -n "$VERBOSE" ] && printf '\n' >&2
     GH="$1"
     URL="$2"
     REF="$3"
     SHA1="$4"
+    "$0" --upload-commit --verbose "$GH" "$URL" "$SHA1" # FIXME: verbose
+    if jq -n '{ ref: $ref, sha: $sha }' \
+        --arg ref "$REF" \
+        --arg sha "$SHA1" \
+        | ([ -n "$VERBOSE" ] && tee /dev/stderr) \
+        | curl -fs "https://api.github.com/repos/$GH/git/refs"; then
+        printf 'Notice: \e[32mPush (creation) successful!\e[0m %s is now at %s on %s.\n' "$REF" "$SHA1" "$URL" >&2
+        printf 'Notice: Please git fetch by yourself.\n' >&2
+        exit 0
+    fi
+    PREV="$(curl -fsS "https://api.github.com/repos/$GH/git/$REF" | jq -r '.object.sha')"
+    if jq -n '{ force: false, sha: $sha }' \
+        --arg sha "$SHA1" \
+        | ([ -n "$VERBOSE" ] && tee /dev/stderr) \
+        | curl -fs -X PATCH "https://api.github.com/repos/$GH/git/$REF" \
+        | ([ -n "$VERBOSE" ] && tee /dev/stderr); then
+        printf 'Notice: \e[32mPush successful!\e[0m %s is now at %s on %s.\n' "$REF" "$SHA1" "$URL" >&2
+        printf 'Notice: %s was previously at %s.\n' "$REF" "$PREV" >&2
+        printf 'Notice: Please git fetch by yourself.\n' >&2
+        exit 0
+    fi
+    if jq -n '{ force: true, sha: $sha }' \
+        --arg sha "$SHA1" \
+        | ([ -n "$VERBOSE" ] && tee /dev/stderr) \
+        | curl -fs -X PATCH "https://api.github.com/repos/$GH/git/$REF" \
+        | ([ -n "$VERBOSE" ] && tee /dev/stderr); then
+        printf 'Notice: \e[32mForce push successful!\e[0m %s is now at %s on %s.\n' "$REF" "$SHA1" "$URL" >&2
+        printf 'Notice: %s was previously at %s.\n' "$REF" "$PREV" >&2
+        printf 'Notice: Please git fetch by yourself.\n' >&2
+        exit 0
+    fi
+    exit 0
+fi
+if [ "$#" -gt 0 ] && [ "$1" = "--upload-commit" ]; then
+    shift
+    [ "$1" = "--verbose" ] && VERBOSE=YES && shift
+    [ -n "$VERBOSE" ] && printf '%q' "$0" >&2
+    [ -n "$VERBOSE" ] && printf ' %q' "$@" >&2
+    [ -n "$VERBOSE" ] && printf '\n' >&2
+    GH="$1"
+    URL="$2"
+    SHA1="$3"
     TOKEN="$(cat ~/.hub-sync)" # FIXME: token
 
-    if curl -fs -o /dev/null "https://api.github.com/repos/$GH/git/trees/$T" -H "Authorization: token $TOKEN"
+    if curl -fs -o /dev/null "https://api.github.com/repos/$GH/git/commits/$SHA1" -H "Authorization: token $TOKEN"; then
+        printf 'Notice: \e[33mCommit %s is already on GitHub.\e[0m\n' "$SHA1" >&2
+        exit 0
+    fi
+    [ -n "$VERBOSE" ] && printf 'Info: Commit %s non-existant, will upload later.\n' "$SHA1" >&2
+    git show -s --format="%P" "$SHA1" | (
+    if [ -n "$VERBOSE" ]; then
+        xargs -r -n 1 "$0" --upload-commit --verbose "$GH" "$URL"
+    else
+        xargs -r -n 1 "$0" --upload-commit --verbose "$GH" "$URL"
+    fi
+    )
+    TREE="$(git rev-parse "$SHA1^{tree}")"
+    if ! curl -fs -o /dev/null "https://api.github.com/repos/$GH/git/trees/$TREE" -H "Authorization: token $TOKEN"; then
+        [ -n "$VERBOSE" ] && printf 'Info: Uploading tree %s.\n' "$TREE" >&2
+        TC="$(GIT_AUTHOR_NAME=author \
+            GIT_AUTHOR_EMAIL=author@example.com \
+            GIT_AUTHOR_DATE='1970-01-01T00:00:00Z' \
+            GIT_COMMITTER_NAME=committer \
+            GIT_COMMITTER_EMAIL=committer@example.com \
+            GIT_COMMITTER_DATE='1970-01-01T00:00:00Z' \
+            git commit-tree "$SHA1^{tree}" -m 'tmp')"
+        git push --force "$URL" "$TC:refs/tags/git-fancy-push/tmp-$$"
+        git push --delete "$URL" "refs/tags/git-fancy-push/tmp-$$"
+        [ -n "$VERBOSE" ] && printf 'Info: Tree %s uploaded.\n' "$TREE" >&2
+    fi
+    [ -n "$VERBOSE" ] && printf 'Info: Uploading commit %s.\n' "$SHA1" >&2
+    git cat-file commit "$SHA1" | awk '
+        BEGIN { a=0; }
+        /^$/ { a=1; }
+        { if (a >= 2) print $0; if (a) a++; }
+    ' | jq -Rs '
+            {
+                message: .,
+                tree: $tree,
+                parents: $ARGS.positional,
+                author: { name: $an, email: $ae, date: $aI },
+                committer: { name: $cn, email: $ce, date: $cI },
+                signature: $gpgsig,
+            }
+            | if $gpgsig == "" then del(.signature) else . end
+        ' \
+            --arg tree "$(git rev-parse "$SHA1^{tree}")" \
+            --arg an "$(git show -s --format="%an" "$SHA1")" \
+            --arg ae "$(git show -s --format="%ae" "$SHA1")" \
+            --arg aI "$(git show -s --format="%aI" "$SHA1")" \
+            --arg cn "$(git show -s --format="%cn" "$SHA1")" \
+            --arg ce "$(git show -s --format="%ce" "$SHA1")" \
+            --arg cI "$(git show -s --format="%cI" "$SHA1")" \
+            --arg gpgsig "$(git cat-file commit "$SHA1" | awk '
+                    BEGIN { a=0; }
+                    ! /^ / { if (a) exit; }
+                    /^gpgsig / { a=1; sub(/^gpgsig /, "", $0); print $0; }
+                    { if (a) print $0; }
+                ')" \
+            --args $(git show -s --format="%P" "$SHA1") \
+        | ([ -n "$VERBOSE" ] && tee /dev/stderr) \
+        | curl -fsS -d @- -X POST "https://api.github.com/repos/$GH/git/commits" -H "Authorization: token $TOKEN" \
+        | ([ -n "$VERBOSE" ] && tee /dev/stderr) \
+        | jq -r '.sha' | (
+            read -r sh;
+            if ! [ "$SHA1" = "$sh" ]; then
+                printf 'Error: \e[31mCannot upload commit %s: SHA-1 mismatch.\e[0m\n' "$SHA1" >&2
+                printf 'Error: Usually it'\''s due to the mergetag header.\n' >&2
+                exit 1
+            fi
+            )
+    printf 'Notice: Commit %s uploaded successfully.\n' "$SHA1" >&2
     exit 0
 fi
 
@@ -47,6 +153,8 @@ set -e
 
 # Check if no shallow update
 grep -q '\s\[remote rejected\] (shallow update not allowed)$' "$TLOG" || exit "$R"
+
+printf 'Notice: \e[32mKeep Calm! git-fancy-push has started to address this problem.\e[0m' >&2
 
 awk '
     /^To/ { gh=""; u=""; }
@@ -79,8 +187,8 @@ awk '
     }
 ' "$TLOG" | (
 if [ -n "$VERBOSE" ]; then
-    tee /dev/stderr | xargs -L 1 "$0" --execute --verbose
+    tee /dev/stderr | xargs -r -L 1 "$0" --update-ref --verbose
 else
-    xargs -L 1 "$0" --execute
+    xargs -r -L 1 "$0" --update-ref
 fi
 )
